services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mailpuff:latest
    container_name: MailPuff
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - "8080:8080"