services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mail-to-tg:latest
    container_name: mail-to-tg
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - "8080:8080"